services:
  trainerdb:
    image: mongo
  reviewdb:
    image: mongo
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest 
  

  trainerservice.api:
    image: ${DOCKER_REGISTRY-}trainerserviceapi
    build:
      context: .
      dockerfile: Services/TrainerService/TrainerService.API/Dockerfile

  reviewservice.api:
    image: ${DOCKER_REGISTRY-}reviewserviceapi
    build:
      context: .
      dockerfile: Services/ReviewService/ReviewService.API/Dockerfile

  reviewservice.grpc:
    image: ${DOCKER_REGISTRY-}reviewservicegrpc
    build:
      context: .
      dockerfile: Services/ReviewService/ReviewService.GRPC/Dockerfile


  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Security/IdentityServer/Dockerfile

volumes:
  trainermongo_data:
  reviewmongo_data:
  mssql_data:  

